// Builds the read-only source mirror published alongside a plugin release
// (see mirrorReadme below for what that repository is and why it exists).
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

// A POSIX-style path relative to apps/obsidian. Excludes build output,
// dependencies, and VCS metadata (none of which are sources), plus
// styles.css: it is generated by scripts/generate-doc-css.ts from
// packages/platforms/markii-react's doc.css, not authored in this
// workspace, so shipping it as "source" in a read-only mirror would be
// misleading about where it comes from.
export function isSnapshotSource(relPath: string): boolean {
  if (
    relPath.startsWith('dist/') ||
    relPath.startsWith('node_modules/') ||
    relPath.startsWith('.git/')
  ) {
    return false;
  }
  if (relPath === 'styles.css') {
    return false;
  }
  // The root README is the authored source `mirrorReadme` composes the
  // mirror's own README from, and that composed file is written separately.
  // Copying it here too would place the monorepo wording in the mirror and
  // list the path twice.
  if (relPath === 'README.md') {
    return false;
  }
  if (relPath === '.DS_Store' || relPath.endsWith('/.DS_Store')) {
    return false;
  }
  return true;
}

/**
 * The mirror repository's README: the authored `apps/obsidian/README.md`,
 * with `{{VERSION}}` filled in, wrapped in the two sections that only make
 * sense in the mirror. One authored source, so the install steps, command
 * list and settings rules cannot drift between the monorepo and the mirror.
 */
const README_PATH = new URL('../../README.md', import.meta.url);

const MIRROR_INTRO = `# Markii for Obsidian

This repository is a read-only release mirror. The source of truth is the main
Markii repository at https://github.com/markii-org/markii, where the plugin
lives in \`apps/obsidian\`.

Everything here is generated by CI when a plugin release is tagged. The
contents are replaced wholesale each time, so anything pushed here directly is
lost at the next release.

Issues and pull requests belong on the main repository:
https://github.com/markii-org/markii. Pull requests opened here cannot be
merged.
`;

const MIRROR_SOURCE_NOTE = `## About the source in this repository

The files beside this README are the plugin's TypeScript sources, copied from
\`apps/obsidian\` in the main repository. They are here to read. They do not
build on their own: the plugin is built from the monorepo, where its workspace
dependencies live.
`;

export function mirrorReadme(version: string): string {
  const authored = readFileSync(README_PATH, 'utf8');

  // Drop the authored title and its lead paragraphs: the mirror opens with
  // its own explanation of what the repository is. Everything from the first
  // `## ` heading onward is shared text.
  const bodyStart = authored.indexOf('\n## ');
  const body = bodyStart === -1 ? authored : authored.slice(bodyStart + 1);

  const licenseStart = body.indexOf('## License');
  const beforeLicense =
    licenseStart === -1 ? body : body.slice(0, licenseStart);
  const license = licenseStart === -1 ? '' : body.slice(licenseStart);

  return [
    MIRROR_INTRO,
    beforeLicense.trimEnd(),
    '',
    MIRROR_SOURCE_NOTE,
    license.trimEnd(),
    '',
  ]
    .join('\n')
    .replace(/\{\{VERSION\}\}/g, version);
}

// Directory names that are never descended into. This is a prune during the
// walk rather than a filter after it: node_modules is an enormous tree in CI,
// and one unreadable entry inside it would throw and fail a release that never
// wanted to read it in the first place.
const PRUNED_DIRECTORIES = new Set(['dist', 'node_modules', '.git']);

function listAllRelative(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(base, full).split(sep).join('/');
    if (entry.isDirectory()) {
      if (PRUNED_DIRECTORIES.has(entry.name)) {
        continue;
      }
      results.push(...listAllRelative(full, base));
    } else if (entry.isFile()) {
      results.push(rel);
    }
  }
  return results;
}

export function buildMirrorSnapshot(options: {
  appDir: string;
  outDir: string;
  licensePath: string;
  version: string;
}): { files: string[] } {
  const { appDir, outDir, licensePath, version } = options;

  mkdirSync(outDir, { recursive: true });

  const allRelative = listAllRelative(appDir, appDir);
  const sourceRelative = allRelative.filter((rel) => isSnapshotSource(rel));

  for (const rel of sourceRelative) {
    const dest = join(outDir, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(join(appDir, rel), dest);
  }

  copyFileSync(licensePath, join(outDir, 'LICENSE'));
  writeFileSync(join(outDir, 'README.md'), mirrorReadme(version), 'utf8');

  const files = [...sourceRelative, 'LICENSE', 'README.md'];
  files.sort();
  return { files };
}
