// Builds the read-only source mirror published alongside a plugin release
// (see mirrorReadme below for what that repository is and why it exists).
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

// A POSIX-style path relative to apps/obsidian. Excludes build output,
// dependencies, and VCS metadata (none of which are sources), plus
// styles.css: it is generated by scripts/generate-doc-css.ts from
// packages/platforms/markii-react's doc.css, not authored in this
// workspace, so shipping it as "source" in a read-only mirror would be
// misleading about where it comes from.
export function isSnapshotSource(relPath: string): boolean {
  if (
    relPath.startsWith('dist/') ||
    relPath.startsWith('node_modules/') ||
    relPath.startsWith('.git/')
  ) {
    return false;
  }
  if (relPath === 'styles.css') {
    return false;
  }
  if (relPath === '.DS_Store' || relPath.endsWith('/.DS_Store')) {
    return false;
  }
  return true;
}

export function mirrorReadme(version: string): string {
  return `# Markii for Obsidian

This repository is a read-only release mirror. The source of truth is the main
Markii repository at https://github.com/markii-org/markii, where the plugin
lives in \`apps/obsidian\`.

Everything here is generated by CI when a plugin release is tagged. The
contents are replaced wholesale each time, so anything pushed here directly is
lost at the next release.

Issues and pull requests belong on the main repository:
https://github.com/markii-org/markii. Pull requests opened here cannot be
merged.

## Install

Markii is not in the Obsidian community catalogue yet. Two routes install it
from this repository's releases.

### Zip (recommended)

1. Download \`markii-${version}.zip\` from the Releases page of this repository.
2. Extract it into your vault's plugin folder, \`<vault>/.obsidian/plugins/\`.
   The archive holds a single \`markii/\` folder, so you should end up with
   \`<vault>/.obsidian/plugins/markii/\`.
3. Restart Obsidian, or reload the community plugin list.
4. Open Settings, go to Community plugins, and enable Markii.

To update, download the newer zip and extract it over the same folder, then
reload Obsidian.

This is the only route that includes the esbuild-wasm runtime that component
packs need in order to compile from source, so it is the one to use if you
install any component pack that does not ship a prebuilt \`webview.js\`.

### BRAT

1. Install the [obsidian42-BRAT](https://github.com/TfTHacker/obsidian42-brat)
   plugin from the community catalogue.
2. In BRAT's settings, add a beta plugin using this repository's URL,
   \`https://github.com/markii-org/markii-obsidian\`.
3. BRAT fetches \`manifest.json\`, \`main.js\`, and \`styles.css\` from the
   latest release and keeps them updated automatically.

With the BRAT install, note scripts and every built-in component work the
same as the zip install. The one thing it cannot do is compile a component
pack that ships source rather than a prebuilt \`webview.js\`: that needs the
esbuild-wasm runtime, which only the zip carries. Use the zip if you plan to
install a pack like that.

To add pack compilation to a BRAT install without reinstalling, download the
zip, copy its \`esbuild-wasm\` folder into your plugin folder next to
\`main.js\`, and reload Obsidian. The plugin looks for that folder at load
time, so this one copy enables compiling every pack. BRAT updates leave the
folder in place.

Markii is desktop only. It runs note scripts inside a terminatable isolate and
compiles component packs in process, and Obsidian on mobile supports neither.

## About the source in this repository

The files beside this README are the plugin's TypeScript sources, copied from
\`apps/obsidian\` in the main repository. They are here to read. They do not
build on their own: the plugin is built from the monorepo, where its workspace
dependencies live.

## License

MIT, the same as the main repository. See LICENSE.
`;
}

// Directory names that are never descended into. This is a prune during the
// walk rather than a filter after it: node_modules is an enormous tree in CI,
// and one unreadable entry inside it would throw and fail a release that never
// wanted to read it in the first place.
const PRUNED_DIRECTORIES = new Set(['dist', 'node_modules', '.git']);

function listAllRelative(dir: string, base: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = relative(base, full).split(sep).join('/');
    if (entry.isDirectory()) {
      if (PRUNED_DIRECTORIES.has(entry.name)) {
        continue;
      }
      results.push(...listAllRelative(full, base));
    } else if (entry.isFile()) {
      results.push(rel);
    }
  }
  return results;
}

export function buildMirrorSnapshot(options: {
  appDir: string;
  outDir: string;
  licensePath: string;
  version: string;
}): { files: string[] } {
  const { appDir, outDir, licensePath, version } = options;

  mkdirSync(outDir, { recursive: true });

  const allRelative = listAllRelative(appDir, appDir);
  const sourceRelative = allRelative.filter((rel) => isSnapshotSource(rel));

  for (const rel of sourceRelative) {
    const dest = join(outDir, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(join(appDir, rel), dest);
  }

  copyFileSync(licensePath, join(outDir, 'LICENSE'));
  writeFileSync(join(outDir, 'README.md'), mirrorReadme(version), 'utf8');

  const files = [...sourceRelative, 'LICENSE', 'README.md'];
  files.sort();
  return { files };
}
